mysite/food/urls.py
from . import views
from django.urls import path

# adding namespace
app_name = 'food'
urlpatterns = [
     # for functional-based view
    # path('', views.index, name='index'), #/food/
    # for class-based view (use view_name.as_view())
    path('', views.IndexClassView.as_view(), name='index'), #/food/
    #/food/1
    # path('<int:item_id>/', views.detail, name='detail'),
    # for class-based view
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('item/', views.item, name='item'),
    # add items
    # path('add/', views.create_item, name='create_item'),
    # modifying url to go with the class-base view
    path('add/', views.CreateItem.as_view(), name='create_item'),
    #edit
    path('update/<int:id>/', views.update_item, name='update_item'),
    # delete
    path('delete/<int:id>/', views.delete_item, name='delete_item')
]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# model are blueprints to create database tables, they define
# the structure of how the models will be created (eg it defines
# the table columns, names, datatypes, maximum values it can contain, etc)
# Also linking the Item Model to the default User model, this can be done 
# by connecting the User model as a foreign key to the Item model
class Item(models.Model):
    # defining the string representation of the models
    def __str__(self):
        return self.item_name
    # user_name is a foreign key on the Item model from the User model
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png")
 
    # this function tells the app to redirect the user to the item detail page, when a new item is added
    # kwargs (keyword argument) was used to pass in the pk of the added item which was gotten by 'self.pk'
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/food/forms.py
from django import forms
from .models import Item

# create form class to add new item 
class ItemForm(forms.ModelForm):
    # the Meta class is a class which gives more information on the ItemForm class
    class Meta:
        model = Item
        fields = ['item_name','item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
# for class-based view
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
# def index(request):
#     # Get all the items from the DB
#     item_list = Item.objects.all()
#     # load the html template
#     template = loader.get_template('food/index.html')
#     # the template needs a context, which is the data from the db
#     # the context can be empty.
#     context = {

#     } 
#     # rendering the template by passing the context and request
#     return HttpResponse(template.render(context, request))

# def index(request):
#     # Get all the items from the DB
#     item_list = Item.objects.all()
#     # load the html template
#     template = loader.get_template('food/index.html')
#     # specifying the context
#     context = {
#         'item_list':item_list,
#     } 
#     # rendering the template by passing the context and request
#     return HttpResponse(template.render(context, request))


# this view is a django functional view (Main)
# this functional view has been replace with the IndexClassView
# class-based view, hence this index does nothing anymore
def index(request):
    # Get all the items from the DB
    item_list = Item.objects.all()
    # specifying the context
    context = {
        'item_list':item_list,
    } 
    # rendering the template by passing the context and request
    return render(request, 'food/index.html', context)

## converting the index view to a class-based view
## since the view displays a list of items, it can be 
## implmented with clased-based list view
class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

## just a test view
def item(request):
    return HttpResponse('<h1>This is an item views</h1>')

# This view displays a detail view for each item
def detail(request, item_id):
    # get the item whose primary key is the requested item_id
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)

# converting the above detail() function-based view to a class-based view
# This view gives detail of the selected food item
class FoodDetail(DetailView):
    model = Item
    template_name= 'food/detail.html'

# view to add Items to the database via form 
def create_item(request):
   # create a new form object from the ItemForm form in forms.py
   form = ItemForm(request.POST or None)

   if form.is_valid():
       form.save()
       return redirect('food:index')
   # render a template after creating form
   return render(request, 'food/item-form.html', {'form':form})

# this a class-based view replacing the exiting function-based view create_item
# this version of the view will track the user adding the type automatically and 
# assign the user as the author of the post
class CreateItem(CreateView):
    model = Item;
    # note the user_name field was not added to the list manually
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name= 'food/item-form.html'

    # function to accept the form
    def form_valid(self,form):
        # automatically access and assign the user_name 
        # self.request.user gets the name of the logged in user
        form.instance.user_name = self.request.user

        return super().form_valid(form)
    

# view to update an Item in the database
def update_item(request, id):
    # query the db and get the id of the item to update
    item = Item.objects.get(id=id)
    # create a form object and pass in the data retrieved as instance
    form = ItemForm(request.POST or None, instance=item)

    # validate and save the form, then redirect to home or index page
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    # render the form to the item-form.html template and pass the retrived item
    return render(request, 'food/item-form.html', {'form': form, 'item':item})

# # view to delete an Item to the database 
def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item': item})

    

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">DagorisFood</a>
        
        <div class="navbar text-light">
            <a class="nav-item nav-link me-3" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link me-3" href="#">View Item</a>
            <a class="nav-item nav-link me-3" href="#">Delete Item</a>
            <!-- check if the user is logged in and display login or logout link depending on the case -->
            {% if user.is_authenticated %}
                <form id="logout-form" action="{% url 'logout' %}" method="POST" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="nav-item nav-link me-3" style="background:none;border:none;color:inherit;cursor:pointer;padding:0;">
                        Logout
                    </button>
                </form>
                <a class="nav-item nav-link me-3" href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a class="nav-item nav-link me-3" href="{% url 'login' %}">Login</a>
            {% endif %}

            <!-- {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %} -->
        </div>
        </div>
    </nav>
        <!-- display django messages eg when user login -->
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dagoris Food - {{item.item_name}} Meal</title>
</head>
<body>
    {% block body %}
    <div class="container-md">
        <div class="row">
            <div class="col-md-6">
                <img height="300px" src="{{ item.item_image }}" class="card img-thumbnail">
            </div>
            <div class="col-md-6">
                <!-- accessing the functional-based view -->
                <!-- <h1> {{item.item_name}} </h1>
                <h2> {{item.item_desc}} </h2>
                <h3> {{item.item_price}} </h3> -->
                
                <!-- accessing the class-based view context using object -->
                <h1> {{object.item_name}} </h1>
                <h2> {{object.item_desc}} </h2>
                <h3> {{object.item_price}} </h3>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dagoris Food - Best online Food Shop</title>
</head>
<body>

    {% block body %}
    <h1>Welcome to Dagoris Food Hub</h1>
    <!-- returning a list of item, using a for loop, with the django template language -->
     {% for item in item_list %}
     <div class="container-md">
     <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card img-thumbnail" src="{{ item.item_image }}" height="150px"/>
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5> {{item.item_desc}} </h5>
            <h6> {{item.item_price}} </h6>
            <h6>{{ item.user_name }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
     </div>





     <!-- displaying the item id and name -->
        <!-- <ul>
            <li> -->
                <!-- hardcoded url -->
                <!-- <a href="{{item.id}}">{{item.id}} -- {{item.item_name}}</a> -->
                 <!-- removing hardcoded url and adding namespace (food) to url-->
                <!-- <a href="{% url 'food:detail' item.id %}">{{item.id}} -- {{item.item_name}}</a>
            </li>
        </ul> -->
    </div>
     {% endfor %}

    {% endblock %}
</body>
</html>

mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title font-weight-bold display-6">
                        Add New Food Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <!-- csrf_token tage is used for security to prevent cross-site scripting attack -->
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.item_name.id_for_label }}">Item Name:</label>
                            <input type="text" name="{{ form.item_name.name }}" id="{{ form.item_name.id_for_label }}" 
                                   class="form-control" placeholder="{{ form.item_name.label }}" />
                            <!-- Display any errors related to the username field -->
                            <div class="invalid-feedback">
                                {% for error in form.item_name.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.item_desc.id_for_label }}">Item Name:</label>
                            <input type="text" name="{{ form.item_desc.name }}" id="{{ form.item_desc.id_for_label }}" 
                                   class="form-control" placeholder="{{ form.item_desc.label }}" />
                            <!-- Display any errors related to the username field -->
                            <div class="invalid-feedback">
                                {% for error in form.item_desc.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.item_price.id_for_label }}">Item Name:</label>
                            <input type="text" name="{{ form.item_price.name }}" id="{{ form.item_price.id_for_label }}" 
                                   class="form-control" placeholder="{{ form.item_price.label }}" />
                            <!-- Display any errors related to the username field -->
                            <div class="invalid-feedback">
                                {% for error in form.item_price.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.item_image.id_for_label }}">Item Image:</label>
                            <input type="file" name="{{ form.item_image.name }}" id="{{ form.item_image.id_for_label }}" 
                                   class="form-control-file my-2" />
                            <!-- Display any errors related to the item_image field -->
                            <div class="invalid-feedback">
                                {% for error in form.item_image.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-info text-white mt-2">Add New Item</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}